include: package:flutter_lints/flutter.yaml

# pub.dev와 동일한 lint 규칙 사용 (flutter_lints 는 lints 를 포함합니다)
# https://pub.dev/packages/flutter_lints

linter:
  rules:
    # pub.dev static analysis 규칙
    - always_declare_return_types

    # Flutter 관련 추가 규칙
    - use_key_in_widget_constructors
    - use_build_context_synchronously
    - avoid_print
